name: "Debug: On Pull Request"
run-name: "Debug jobs triggered on Pull Requests"

on: pull_request

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub vars
        run: |
          echo "github: ${{ github }}"
          echo "github.action: ${{ github.action }}"
          echo "github.action_path: ${{ github.action_path }}"
          echo "github.action_ref: ${{ github.action_ref }}"
          echo "github.action_repository ${{ github.action_repository }}"
          echo "github.action_status: ${{ github.action_status }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.actor_id: ${{ github.actor_id }}"
          echo "github.api_url: ${{ github.api_url }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.env: ${{ github.env }}"
          echo "github.event: ${{ github.event }}"
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event.pull_request ${{ github.event.pull_request }}"
          echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "github.event.pull_request.merged: ${{ github.event.pull_request.merged }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event_path: ${{ github.event_path }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.job: ${{ github.job }}"
          echo "github.path: ${{ github.path }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref_protected: ${{ github.ref_protected }}"
          echo "github.ref_type: ${{ github.ref_type }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.repository_id: ${{ github.repository_id }}"
          echo "github.repositoryUrl: ${{ github.repositoryUrl }}"
          echo "github.run_attempt: ${{ github.run_attempt }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.run_number: ${{ github.run_number }}"
          echo "github.triggering_actor: ${{ github.triggering_actor }}"
          echo "github.workflow: ${{ github.workflow }}"
          echo "github.workflow_ref: ${{ github.workflow_ref }}"
          echo "github.workspace: ${{ github.workspace }}"
      
      - name: Runner vars
        run: |
          echo "runner: ${{ runner }}"
          echo "runner.arch: ${{ runner.arch }}"
          echo "runner.debug: ${{ runner.debug }}"
          echo "runner.environment: ${{ runner.environment }}"
          echo "runner.name: ${{ runner.name }}"
          echo "runner.os: ${{ runner.os }}"
          echo "runner.temp: ${{ runner.temp }}"
          echo "runner.tool_cache: ${{ runner.tool_cache }}"
          echo "runner.workspace: ${{ runner.workspace }}"
      
      - name: Job vars
        run: |
          echo "job: ${{ job }}"
          echo "job.check_run_id: ${{ job.check_run_id }}"
          echo "job.status: ${{ job.status }}"
